### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by disa-mhembere** [neurodata/R-RerF#11]
I think the README should state this clearly

**Comment by disa-mhembere** [comment]
Oh I see there is *USE: * and no *install*. Why don't you make it `devtools` installable?

**Comment by disa-mhembere** [comment]
The README says download `rfr_function.R` and all that but it seems `github_install` works. Maybe just your docs 😁  and tell me what to try as a user from the README. Installed but don't know what to do now

**Comment by jbrowne6** [comment]
You beat me to it.  One of my Asana tasks this week is to update the 3 month old readme.  I’ll update later today to reflect the current state of the system.  Thanks for trying it though.

James.

**Comment by disa-mhembere** [comment]
It all works!
