### ISSUE TITLE
Update DESCPRITION file

### ISSUE THREAD

**Issue by ttomita** [neurodata/R-RerF#12]
1. Add @jovo as an author of type "ths" (see [here](https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf))
2. Add URL that links to this repository.
3. Tag CRAN version #

**Comment by ttomita** [comment]
@jovo look at the top of README. Is that what you meant by "tag the CRAN version #?"

**Comment by jovo** [comment]
i meant to use the "release" functionality in github, though i do like the badge :)

**Comment by falkben** [comment]
we will tag the next release when we publish it in a month
