### ISSUE TITLE
add zenodo DOI

### ISSUE THREAD

**Issue by jovo** [neurodata/R-RerF#74]

**Comment by falkben** [comment]
zenodo wasn't connected to lumberjack/rerf, so I connected it.  however, it's not recognizing the existing release on github, I think we'd need to register a new release in order for zenodo to "mint" a DOI for us.  Since we're just a few days from v2.0.0 I think we should just wait until then.

**Comment by jovo** [comment]
Good

**Comment by falkben** [comment]
10.5281/zenodo.1933344
