### ISSUE TITLE
Package installation error

### ISSUE THREAD

**Issue by ttomita** [neurodata/R-RerF#8]
@jbrowne6 

Here is the log:

Installing RcppArmadillo
'/usr/local/Cellar/r/3.3.2/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/4r/ywwl5n7s58g2y4sds1857vq00000gn/T/RtmpGzGSGo/devtools19cf4fb50029/RcppArmadillo'  \
  --library='/usr/local/lib/R/3.3/site-library' --install-tests 

* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking whether g++ version is sufficient... checking LAPACK_LIBS... system LAPACK found
checking for macOS... found
configure: WARNING: OpenMP unavailable and turned off.
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
clang++ -std=c++11 -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include -I"/usr/local/lib/R/3.3/site-library/Rcpp/include"  -std=c++11 -fPIC  -g -O2 -c RcppArmadillo.cpp -o RcppArmadillo.o
RcppArmadillo.cpp:22:10: fatal error: 'RcppArmadillo.h' file not found
#include <RcppArmadillo.h>
         ^
1 error generated.
make: *** [RcppArmadillo.o] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/usr/local/lib/R/3.3/site-library/RcppArmadillo’
* restoring previous ‘/usr/local/lib/R/3.3/site-library/RcppArmadillo’
Installation failed: Command failed (1)
'/usr/local/Cellar/r/3.3.2/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/4r/ywwl5n7s58g2y4sds1857vq00000gn/T/RtmpGzGSGo/devtools19cf2938cb73/neurodata-R-RerF-96c97cf/rerf'  \
  --library='/usr/local/lib/R/3.3/site-library' --install-tests 

* installing *source* package ‘rerf’ ...
** libs
make: Nothing to be done for `all'.
installing to /usr/local/lib/R/3.3/site-library/rerf/libs
** R
** preparing package for lazy loading
** help
No man pages found in package  ‘rerf’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.3/site-library/rerf/libs/rerf.so':
  dlopen(/usr/local/lib/R/3.3/site-library/rerf/libs/rerf.so, 6): no suitable image found.  Did find:
	/usr/local/lib/R/3.3/site-library/rerf/libs/rerf.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/usr/local/lib/R/3.3/site-library/rerf/libs/rerf.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/3.3/site-library/rerf’
Installation failed: Command failed (1)

**Comment by ttomita** [comment]
This is on macOS

**Comment by ttomita** [comment]
I think I had this error when I had installed RcppArmadillo previously. I remember having to specify the compiler flags in a ~/.R/Makevars file. I think I went over this with you. For the package, you might have to include a Makevars file:

https://cran.r-project.org/doc/manuals/R-exts.html#Using-Makevars

**Comment by ttomita** [comment]
Nevermind the RcppArmadillo issue was caused by my own Makevars file being wrong. That problem is fixed. However I still can't install. Here is what the log says now:

Downloading GitHub repo neurodata/R-Rerf@master
from URL https://api.github.com/repos/neurodata/R-Rerf/zipball/master
Installing rerf
'/usr/local/Cellar/r/3.3.2/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/4r/ywwl5n7s58g2y4sds1857vq00000gn/T/RtmpfEtuAh/devtools21aa1ed93e58/neurodata-R-RerF-96c97cf/rerf'  \
  --library='/usr/local/lib/R/3.3/site-library' --install-tests 

* installing *source* package ‘rerf’ ...
** libs
make: Nothing to be done for `all'.
installing to /usr/local/lib/R/3.3/site-library/rerf/libs
** R
** preparing package for lazy loading
** help
No man pages found in package  ‘rerf’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.3/site-library/rerf/libs/rerf.so':
  dlopen(/usr/local/lib/R/3.3/site-library/rerf/libs/rerf.so, 6): no suitable image found.  Did find:
	/usr/local/lib/R/3.3/site-library/rerf/libs/rerf.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/usr/local/lib/R/3.3/site-library/rerf/libs/rerf.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/3.3/site-library/rerf’
Installation failed: Command failed (1)

**Comment by ttomita** [comment]
This does not seem to be a system-specific issue as I also couldn't install on MARCC

**Comment by jbrowne6** [comment]
Package installs in latest version on multiple OSes.
